name: Daily Weather Scraper
on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:
jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch Data
        run: |
          curl -s "https://open-meteo.com" > raw.json
          if [ ! -f weather_archive.csv ]; then echo "scrape_date,max_temp,min_temp" > weather_archive.csv; fi
          echo "$(date +'%Y-%m-%d'),$(grep -o '"temperature_2m_max":\[[^]]*\]' raw.json | cut -d'[' -f2 | cut -d',' -f1),$(grep -o '"temperature_2m_min":\[[^]]*\]' raw.json | cut -d'[' -f2 | cut -d',' -f1)" >> weather_archive.csv
      - name: Save
        run: |
          git config --global user.name "Automation"
          git config --global user.email "actions@github.com"
          git add weather_archive.csv
          git commit -m "sync" || exit 0
          git push
